.TH "pyjigdo" "1" "0.3.0" "Fedora Unity" ""
.SH "NAME"
.LP 
pyjigdo \- PYthon JIGsaw DOwnloader
.SH "SYNTAX"
.LP 
pyjigdo [\fIoption\fP]... \fIjigdoURL\fP
.SH "DESCRIPTION"
.LP 
PyJigdo is a Python rewrite of the popular Jigdo distribution framework. It has also been slightly modified to add some extra features.
.SH "EXAMPLES"
.LP 
Interactively download an ISO image listed in the specified .jigdo file or URL.
.IP 
pyjigdo\ http://jigdo.fedoraunity.org/templates/20080331/Fedora\-Unity\-20080331\-8.jigdo
.LP 
Save \fItime\fP and \fIbandwidth\fP by not downloading parts you already have available locally. Point \-\-scan\-dir at base dirs and/or \-\-scan\-iso at ISO images. One of these options should \fIalways\fP be used when possible, and is a primary feature of using Jigdo over other download methods.
.IP 
pyjigdo \-\-scan\-dir "/media/Fedora\ 8\ i386\ DVD" Fedora\-Unity\-20080331\-8.jigdo
.br 
pyjigdo \-\-scan\-iso ~/downloads/Fedora\-8\-i386\-DVD.iso Fedora\-Unity\-20080331\-8.jigdo
.LP 
Automatically start downloading ISO image #6 (e.g. the i386 DVD ISO).
.IP 
pyjigdo \-\-image 6 Fedora\-Unity\-20080331\-8.jigdo
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-cli\fR
Use the CLI rather then GUI (default)
.TP 
\fB\-\-gui\fR
Force pyJigdo to use the GUI. Does not fallback to CLI and thus shows GUI related errors. (pyjigdo\-gui default)
.TP 
\fB\-\-list\-images\fR
List available images for a given Jigdo file.
.TP 
\fB\-d DEBUGLEVEL, \-\-debug=DEBUGLEVEL\fR
Set debugging level (0 by default)
.TP 

\fB\-c [\fIconfig file\fP], \-\-config=[\fIconfig file\fP]\fR
PyJigdo configuration file to use
.TP 
\fB\-\-dest\-dir=[\fIdirectory\fP], \-\-destination\-directory=[\fIdirectory\fP]\fR
Destination directory for products. (Default: /tmp/dl)
.TP 
\fB\-\-work\-dir=[\fIdirectory\fP], \-\-working\-directory=[\fIdirectory\fP]\fR
Working directory. (Default: /tmp/dl/pyjigdo\-data)
.TP 

\fB\-j [\fIurl\fP], \-\-jigdo=[\fIurl\fP]\fR
Location of jigdo file.
.TP 
\fB\-\-info\fR
Print information about the jigdo image and exit.
.TP 
\fB\-\-fallback=[number of tries]\fR
Number of public mirrors to try before using a fallback mirror. (Default: 5)
.TP 
\fB\-t [number of seconds], \-\-timeout=[number of seconds]\fR
Number of seconds to wait before switching to different slice source. (Default: 15)
.TP 

\fB\-i [image number], \-\-image=[image number]\fR
Download or Host given image number(s).
.TP 
\fB\-a, \-\-all\fR
Download or Host all images defined in jigdo.
.TP 
\fB\-s [directory], \-\-scan\-dir=[directory]\fR
Scan given directory for files needed by selected image(s).
.TP 
\fB\-\-scan\-iso=[iso image]\fR
Mount and then scan existing ISO images for files needed by selected image(s).
.TP 

\fB\-\-version\fR
output version information and exit
.TP 
\fB\-h, \-\-help\fR
show help message and exit
.SH "FILES"
.LP 
\fI /etc/pyjigdo/pyjigdo.conf\fP 
.br 
\fI ./pyjigdo\-data/\fP
.br 
\fI ./pyjigdo.log\fP
.SH "AUTHORS"
.LP 
Jonathan Steffan, Jeroen van Meeuwen, Ignacio Vazquez\-Abrams, Stewart Adam.
.SH "BUGS"
.LP 
Report bugs at http://bugzilla.redhat.com/ .
.SH "SEE ALSO"
.LP 
pyjigdo\-conf(5) pyjigdo(8) wget(1)
